Repository cjstk7168/AlgorithmStudy, pull requests merged in 2020-02, with the labels that each got.

#17 Update README.md
  README.md
Labels: documentation

#24 add question study 4
  study4_200225/README.md
Labels: question

#3 study1 - answer 1, 2
  study1_200204/kyungyeon.js
Labels: answer

#7 study1 - answer 1, 2
  study1_200204/seongha.js
Labels: answer

#21 Study2- answer 1, 2
  study2_200211/kyungyeon.js
Labels: answer
